# -*- coding: utf-8 -*-
"""2_Event_Study_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DC9-1aIgF2dnA72OHdZXGn1JqlfU0XIS
"""

import streamlit as st
import pandas as pd
import os
import yfinance as yf
from utils import load_stock_data, load_market_data, calculate_market_model_car, calculate_fama_french_car, plot_car_graph, plot_ci_graph

# Set Page Config
st.set_page_config(
    page_title="Event Study Dashboard",
    page_icon="📈",
    layout="centered"
)

# Helper function to trigger analysis when model changes
def trigger_analysis():
    st.session_state["run_analysis"] = True

st.title("📈 Event Study Dashboard")

# Load event data
event_data = pd.read_csv("event_data.csv", parse_dates=["event_date"])

# Sidebar filters
industries = event_data["industry"].unique()
selected_industry = st.sidebar.selectbox("Select Industry", industries)

filtered_data = event_data[event_data["industry"] == selected_industry]
tickers = filtered_data["ticker"].unique()
selected_ticker = st.sidebar.selectbox("Select Ticker", tickers)

event_dates = filtered_data[filtered_data["ticker"] == selected_ticker]["event_date"].dt.date.unique()
selected_event_date = st.sidebar.selectbox("Select Event Date", event_dates)

# Model selection (with auto-trigger)
model_choice = st.sidebar.radio(
    "Choose Model",
    ["Market Adjusted Model", "Fama French 3-Factor Model"],
    key="model_choice",
    on_change=trigger_analysis
)

# Analyze Button
analyze = st.sidebar.button("Analyze")

# Main Analysis
if analyze or st.session_state.get("run_analysis", False):
    st.subheader(f"Analysis for {selected_ticker} on {selected_event_date}")

    # Show Logo from local 'logos/' folder
    logo_path = f"logos/{selected_ticker}.png"
    if os.path.exists(logo_path):
        st.image(logo_path, width=150)
    else:
        st.warning("Logo not available for this stock.")

    # 🆕 Stock Snapshot Section
    try:
        ticker_obj = yf.Ticker(selected_ticker)
        stock_info = ticker_obj.info

        # 🏦 Show Stock Quick Overview
        st.markdown("### 🏦 Stock Snapshot")
        col1, col2 = st.columns(2)
        col1.metric("💲 Current Price", f"${stock_info.get('currentPrice', 'N/A')}")
        col2.metric("📈 1-Day Change", f"{stock_info.get('regularMarketChangePercent', 0):.2f}%")

        # 📈 1-Month Price Trend
        st.markdown("### 📈 1-Month Price Trend")
        hist = ticker_obj.history(period="1mo")
        if not hist.empty:
            st.line_chart(hist["Close"])
        else:
            st.warning("Price history unavailable.")

        # 📊 Company Ratios
        st.markdown("### 📊 Company Overview")
        col3, col4 = st.columns(2)
        with col3:
            st.write(f"**Sector:** {stock_info.get('sector', 'N/A')}")
            st.write(f"**Industry:** {stock_info.get('industry', 'N/A')}")
            st.write(f"**Market Cap:** ${stock_info.get('marketCap', 'N/A'):,}")
        with col4:
            st.write(f"**P/E Ratio:** {stock_info.get('trailingPE', 'N/A')}")
            st.write(f"**Dividend Yield:** {stock_info.get('dividendYield', 'N/A')}")

        st.markdown("---")

    except Exception as e:
        st.warning(f"Could not load stock snapshot: {e}")

    # Event Study Analysis
    start_date = pd.to_datetime(selected_event_date) - pd.Timedelta(days=60)
    end_date = pd.to_datetime(selected_event_date) + pd.Timedelta(days=60)

    try:
        stock_data = load_stock_data(selected_ticker, start_date, end_date)
        market_data = load_market_data(start_date, end_date)

        if model_choice == "Market Adjusted Model":
            results = calculate_market_model_car(stock_data, market_data, pd.to_datetime(selected_event_date))
        else:
            results = calculate_fama_french_car(stock_data, pd.to_datetime(selected_event_date))

        # KPI Calculations
        abnormal_returns = results['abnormal_return']
        CAR_final = abnormal_returns.cumsum().iloc[-1] * 100
        normal_return = results['expected_return'].cumsum().iloc[-1] * 100
        actual_return = results['stock_return'].cumsum().iloc[-1] * 100

        # Display KPIs
        st.markdown("### 📊 Event Impact Metrics")
        col5, col6, col7 = st.columns(3)
        col5.metric("📈 Actual Return", f"{actual_return:.2f}%")
        col6.metric("📉 Expected Return (Normal)", f"{normal_return:.2f}%")
        col7.metric("🚀 CAR (Impact)", f"{CAR_final:.2f}%")

        st.markdown("---")

        # Plot CAR Graph
        st.pyplot(plot_car_graph(results))

        # Plot CI Graph
        st.pyplot(plot_ci_graph(results))

        # Reset trigger after successful run
        st.session_state["run_analysis"] = False

    except Exception as e:
        st.error(f"Error during analysis: {e}")