# -*- coding: utf-8 -*-
"""3_Event_Browser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APoNh9mdXRwP35Cc4tmi-mK_243m9-J8
"""

# pages/3_Event_Browser.py

import streamlit as st
import pandas as pd

st.title("🗞️ Event Browser")

event_data = pd.read_csv("event_data.csv", parse_dates=["event_date"])
st.dataframe(event_data)